apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: raghavcluster
  region: ap-south-1
nodeGroups:
  - name: ng1
    desiredCapacity: 2
    instanceType: t2.micro
    ssh:
      publickeyName: 'raghav_new'
  - name: ng2
    desiredCapacity: 1
    instanceType: t2.small
    ssh:
      publickeyName: 'raghav_new'